collections:
  - name: community.general
    version: 4.8.2
  - theforeman.foreman
  - community.crypto
  - ansible.platform.
  - ansible.hub
  - name: ansible.controller
    version: ">=4.6.0"
  - name: ansible.eda
  - name: infra.aap_configuration