collections:
  - name: community.general
    version: 4.8.2
  - theforeman.foreman
  - community.crypto
  - infra.ah_configuration
  - awx.awx
  - name: ansible.eda
  - name: infra.controller_configuration