---
- name: Add the extra environment variable PYTHONWARNINGS to AAP controller
  hosts: localhost

  vars:
    controller_settings:
      - name: "PYTHONWARNINGS"
        value: "ignore:Unverified HTTPS request"

  roles:
    - role: infra.controller_configuration.settings
      when: controller_settings is defined