---
- hosts: localhost
  connection: local

  name: Configure RHEL hosts for Remote Execution (REX) from Satellite
  gather_facts: no

  vars:
    login: &login
      server_url: "https://{{ lookup('env', 'FOREMAN_SERVER_URL') }}"
      username: "{{ lookup('env', 'FOREMAN_USER') }}"
      password: "{{ lookup('env', 'FOREMAN_PASSWORD') }}"
      validate_certs: no

  tasks:

  - name: Debug server_url
    ansible.builtin.debug:
      msg: "Sat url: {{ login.server_url }}"

  - name: Create a RHEL host collection
    theforeman.foreman.host_collection:
      <<: *login
      name: "All RHEL hosts collection"
      description: "All RHEL hosts regardless of Lifecycle Environment"
      organization: "Default Organization"
      state: present
  
  - name: Add hosts to host collection
    ansible.builtin.command: >
      hammer host-collection add-host
      --name "All RHEL hosts collection"
      --organization "Default Organization"
      --host "{{ item }}"
    loop:
      - node1.example.com
      - node2.example.com
      - node3.example.com

  - name: Create a RHEL host group
    theforeman.foreman.hostgroup:
      name: "All RHEL hosts host group"
      state: present

  - name: Add hosts to host group
    theforeman.foreman.host:
      name: "{{ item }}"
      hostgroup: "All RHEL hosts host group"
      state: present
    loop:
      - node1.example.com
      - node2.example.com
      - node3.example.com
